language: node_js
os:
  - linux
  - os
node_js:
  - 6.0.0
install:
  - npm install
  - bower install
before_script:
  - gulp build
script: gulp test
deploy:
  provider: releases
  file:
    - "dist/sinister-chicken-syndicate.js"
    - "dist/sinister-chicken-syndicate.js.map"
  skip_cleanup: true
  on:
    tags: true
