language: node_js
os:
  - linux
  - osx
node_js:
  - 6.0.0
install:
  - npm install
before_script:
  - npm install -g bower
  - bower install
  - gulp build
script: gulp test
deploy:
  provider: releases
  file:
    - "dist/sinister-chicken-syndicate.js"
    - "dist/sinister-chicken-syndicate.js.map"
  skip_cleanup: true
  on:
    tags: true
