version: "{build}"

platform: x64

environment:
  nodejs_version: "6.0.0"

install:
    - npm install
    - bower install

test_script:
    - gulp build
    - gulp test

build: off

branches:
    only:
      - master
